australia = Country.create(:name => "Australia", :code => "AU")
usa = Country.create(:name => "United States", :code => "US")
Rate.create(:currency_code => "EUR", :country => australia, :regular_shipping_rate => "20.00", :express_shipping_rate => "50.00")
Rate.create(:currency_code => "GBP", :country => australia, :regular_shipping_rate => "15.00", :express_shipping_rate => "30.00")
Rate.create(:currency_code => "EUR", :country => usa, :regular_shipping_rate => "22.00", :express_shipping_rate => "52.00")